@startuml

title __REPOS's Class Diagram__\n

  namespace com.kate_chaus.art_orders {
    namespace repos {
      interface com.kate_chaus.art_orders.repos.MessageRepo {
          {abstract} + findAll()
          {abstract} + findByTag()
      }
    }
  }
  

  namespace com.kate_chaus.art_orders {
    namespace repos {
      interface com.kate_chaus.art_orders.repos.OrderApplicationRepo {
          {abstract} + findByArtistSearchAndCreator()
          {abstract} + findByOpenAndArtistSearch()
          {abstract} + findByOpenAndCostLessThanEqualAndArtistSearch()
          {abstract} + findByOpenAndTypeAndArtistSearch()
          {abstract} + findByOpenAndTypeAndCostLessThanEqualAndArtistSearch()
          {abstract} + findByType()
      }
    }
  }
  

  namespace com.kate_chaus.art_orders {
    namespace repos {
      interface com.kate_chaus.art_orders.repos.OrderRepo {
          {abstract} + findByArtistAndStatus()
          {abstract} + findByCustomerAndStatus()
          {abstract} + findByStatus()
          {abstract} + findTop3ByArtistAndStatusOrderByIdDesc()
          {abstract} + findTop3ByCustomerAndStatusOrderByIdDesc()
      }
    }
  }
  

  namespace com.kate_chaus.art_orders {
    namespace repos {
      interface com.kate_chaus.art_orders.repos.SiteRepo {
      }
    }
  }
  

  namespace com.kate_chaus.art_orders {
    namespace repos {
      interface com.kate_chaus.art_orders.repos.UserRepo {
          {abstract} + findByUsername()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
